spring:
  profiles:
    active: default
  application:
    name: vniiftri-solar-positioning
  main:
    banner-mode: off
    web-application-type: none
  output:
    ansi:
      enabled: ALWAYS

vniiftri:
  timezone: 8
  geolocation:
    latitude: 52
    longitude: 104
    altitude: 544 # m
    side-of-the-world-azimuth: 90 # Север: 360, Восток: 90, Юг: 180, Запад: 270 (в градусах °).
  filename: solar_position.txt